version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123FFdf
      POSTGRES_DB: test
    networks:
      - hixcoder
      
networks:
  hixcoder: